### ISSUE TITLE
INFOGRAFIA DE CALIDAD DE SOFTWARE

### ISSUE THREAD

**Issue by MAB288** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-MAB288#1]
[INFOGRAFIA..pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-MAB288/files/15461374/INFOGRAFIA.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y Calificación 17
